### ISSUE TITLE
Are the hilbert representations and policy learned concurrently for zero-shot RL?

### ISSUE THREAD

**Issue by enjeeneer** [seohongpark/HILP#2]
Hi Seohong,

Sorry to bother you with another quick question; I'm trying to replicate your results in my own implementation, but haven't been able to get HILPs to work yet so I'm doing some troubleshooting. 

Algorithm 1 in your paper suggests you train the Hilbert representations to convergence, then use them to train the policy (as opposed to learning them concurrently as per FB). However in the code it looks like you do learn them concurrently:

https://github.com/seohongpark/HILP/blob/a2abbe4cfcced28dbb3bbd937d92040f250eba35/hilp_zsrl/url_benchmark/agent/sf.py#L760-L764

Is the paper or code correct, or have I missed something?

Thanks very much again!

Scott

**Comment by enjeeneer** [comment]
Forget this, I now see that algorithm 1 is not the zero-shot RL pipeline, and you presumably do just learn the policy and successor features / HILPs concurrently. Apologies for the confusion!

**Comment by seohongpark** [comment]
Right, in practice, we train both the policy and representation concurrently. However, gradients do not flow from the policy loss to the representation, so it's also possible to separate them. We haven't tested sequential training, simply because joint training is easier to implement and enables periodic evaluation. Also, in offline RL, it seems quite common to jointly train a policy and a value even when they are separable (e.g., IQL, contrastive RL, etc.).
